max_iteration : 150000
learning_rate : 0.0001
beta1 : 0.5
beta2 : 0.9
decay_rate : .8
dsteps : 5
gsteps : 1
start_dsteps : 10
batch_size : 64
output_size : 160
c_dim : 3
z_dim : 128
df_dim : 64
dof_dim : 1
gf_dim : 64
architecture : "g-resnet5"
kernel : 'rbf'
model : "smmd"
batch_norm : False
with_sn : False
with_learnable_sn_scale : False
with_scaling : True
